#!/usr/bin/python
# -*- coding: UTF-8 -*- 

import argparse
import math
import os
import sys
import time
import shlex
import subprocess

from signal import signal, SIGPIPE, SIG_DFL
signal(SIGPIPE, SIG_DFL)

PROC_BUDDYINFO = "buddyinfo"
PROC_INTERRUPT = "interrupts"
PROC_SOFTIRQS = "softirqs"
CMD_BTT = "btt"
CMD_MPSTAT = "mpstat"
PROC_IRQ_CPU = "irqcpu"

class RunCmd:
	def __init__(self, act):
		self.act = act

	def run(self, cmd):
		print(cmd)
		if self.act == 1:
			subprocess.Popen(shlex.split(cmd), shell=False, stdout=subprocess.PIPE, stderr=subprocess.PIPE)


class BuddyInfo:
	'''
	/proc/buddyinfo show all free memory is divided into 11 block linked lists in the form of power of 2, 
	corresponding to 1, 2, 4, 8, 16, 32, 64, 128, 256, 512 and 1024 page blocks respectively.
	This tool convert the blocks counter to memory size (unit is K/M/G), add time stamp.
	Such as below output (sak buddyinfo -u=K -o=1)
										order      1      2      3      4      5      6      7      8      9      10   11
						Node 0, zone    DMA32      3      1      2      1      4      3      4      6      4      5    611 
	2021-10-14 10:16:18 Node 0, zone    DMA32      12     8      32     32     256    384    1024   3072   4096   10240 2502656 (total:   2521812 K)  
												(3*1*4K)(1*2*4K) ...
	'''
	BUDDY_INFO_MAX_COL = 15
	BUDDY_INFO_KEYWORD = ["Node", ", zone"]

	def __init__(self, args):
		self.ts, self.unit, self.count = args.time, args.unit, args.count
		self.interval, self.org, self.dbg = args.interval, args.orig, args.debug

	def display_time(self, show):
		if show == 1:
			print("%s" % time.strftime("%Y-%m-%d %H:%M:%S", time.localtime())),

	def display_unit(self, unit, size_kb, show):
		if unit == "K":
			print("%6d" % (size_kb)),
		elif unit == "M":
			print("%6.0f" % (size_kb / 1024)),
		else:
			print("%6.0f" % (size_kb / 1024 / 1024)),

		if show == 1:
			print("%s)" % unit)

	def display_original(self, org, ts, info):
		if org == 1:
			prefix_len = 0
			if ts == 1:
				prefix_len = len("yyyy-mm-dd hh:mm:ss ")
			print("%s%s" % (" " * prefix_len, info))

	def get_buddy_info(self):
		f = open('/proc/buddyinfo')
		lines = f.readlines()
		for line in lines:
			line = line.strip("\n")
			line_list = line.split()
			if len(line_list) == self.BUDDY_INFO_MAX_COL \
			and all(i in line for i in self.BUDDY_INFO_KEYWORD):
				self.display_original(self.org, self.ts, line)

				self.display_time(self.ts)
				print("%s %s %s   %6s" % (line_list[0], line_list[1], line_list[2], line_list[3])),

				zone_total = 0
				for idx in range(4, self.BUDDY_INFO_MAX_COL):
					block_cnt = int(line_list[idx])
					pages_cnt = math.pow(2, (idx - 4))
					order_size = block_cnt * pages_cnt * 4
					zone_total = zone_total + order_size

					self.display_unit(self.unit, order_size, 0)
					if self.dbg == 1:
						print("(%5d*%d*4K)" % (block_cnt, pages_cnt)),
				print("(total:"),
				self.display_unit(self.unit, zone_total, 1)

	def run(self):
		if self.count == 0:
			while True:
				self.get_buddy_info()
				time.sleep(self.interval)
		else:
			for i in range(self.count):
				self.get_buddy_info()
				if i == self.count - 1:
					break
				time.sleep(self.interval)

class IrqInfo:
	'''
	sak interrupts: show the difference of /proc/interrupts count within 1 second
	sak softirqs:   show the difference of /proc/softirqs   count within 1 second
	'''
	def get_common_info(self, file):
		with open(self.file, "r") as f:
			header = f.readline().strip("\n")
			return header.strip(), len(header.split())

	def __init__(self, args):
		self.file = "/proc/" + args.proc_file
		self.header, self.cpus = self.get_common_info(self.file)
		self.count, self.interval = args.count, args.interval

	def show_matrix(self, irqs_vec, timestamp, display):
		if display is False:
			return

		print("{0} {1}".format(self.header, timestamp))
		for irqs in irqs_vec:
			for irq in irqs:
				print("{0:9} ".format(irq)),
			print("\n"),
		print("\n")

	def save_irq(self, irqs_vec, irq_desc, irqs):
		record = []
		irq_name = irq_desc + ":"

		if len(irqs) > self.cpus:
			for i in range(self.cpus):
				record.append(irqs[i])

			for i in range(self.cpus, len(irqs)):
				irq_name += (irqs[i] + "_")
			irq_name = irq_name[:-1]
			record.append(irq_name)
		else:
			for irq in irqs:
				record.append(irq)
			record.append(irq_name)

		# print("add record: {0}".format(record))
		irqs_vec.append(record)

	def comb_date_time(self, ts_b, ts_a):
		b_date, b_time = ts_b.split()
		a_date, a_time = ts_a.split()
		if b_date == a_date:
			return "{0} {1} to {2}".format(b_date, b_time, a_time)
		else:
			return "{0} {1} to {2} {3}".format(b_date, b_time, a_date, a_time)

	def get_proc_irqs(self):
		irqs_vec = []
		timestamp = time.strftime("%Y-%m-%d %H:%M:%S", time.localtime())
		with open(self.file, "r") as f:
			lines = f.readlines()
			for line in lines[1: ]:
				line = line.strip("\n").split(":")
				irq_desc = line[0].strip()
				irq_cnt = line[1].split()
				self.save_irq(irqs_vec, irq_desc, irq_cnt)

		self.show_matrix(irqs_vec, timestamp, False)
		return irqs_vec, timestamp
	
	def calc_diff(self, b, a, ts_b, ts_a):
		result_vec = []
		vec_len = len(b)
		for i in range(vec_len):
			line_b = b[i]
			line_a = a[i]
			cnt = len(line_b)
			one_irq = []
			for j in range(cnt - 1):
				diff = int(line_a[j]) - int(line_b[j])
				one_irq.append(str(diff))
			one_irq.append(line_b[-1])
			result_vec.append(one_irq)

		timestamp = self.comb_date_time(ts_b, ts_a)
		self.show_matrix(result_vec, timestamp, True)

	def run(self):
		before, after = [], []
		ts_b, ts_a = "", ""

		if self.count == 0:
			before, ts_b = self.get_proc_irqs()
			while True:
				time.sleep(self.interval)
				after, ts_a = self.get_proc_irqs()

				self.calc_diff(before, after, ts_b, ts_a)
				before = after
				ts_b = ts_a
		else:
			before, ts_b = self.get_proc_irqs()
			for i in range(self.count):
				time.sleep(self.interval)
				after, ts_a = self.get_proc_irqs()

				self.calc_diff(before, after, ts_b, ts_a)
				if i == self.count - 1:
					break

				before = after
				ts_b = ts_a

class Btt:
	'''
	timeout interval blktrace -d /dev/sda
	blkparse -i sda -d sda.blkparse.out
	btt -i sda.blkparse.out -o sda.btt.out
	btt -i sda.blkparse.out -z sda.btt.q2d_latencies
	btt -i sda.blkparse.out -l sda.btt.d2c_latencies
	btt -i sda.blkparse.out -q sda.btt.q2c_latencies
	btt -i sda.blkparse.out -Q sda.btt.active-queue-depth
	'''
	btt_class = {
		"q2d_latencies":      "sec  q2d(AVG)      q2d(MAX)",
		"d2c_latencies":      "sec  d2c(AVG)      d2c(MAX)",
		"q2c_latencies":      "sec  q2c(AVG)      q2c(MAX)",
		"active-queue-depth": "sec  depth(AVG)    depth(MAX)",
	}
	
	def check_blktrace(self):
		target = "{0}.blktrace".format(self.dev)
		files = os.listdir(self.input)
		for file in files:
			if target in file:				
				return True

		return False

	def __init__(self, args):
		if len(args.device) == 0:
			print("invalid device name!")
			sys.exit(-1)

		if args.output == "":
			date = time.strftime("%Y%m%d_%H%M%S", time.localtime())
			self.output = "{0}/btt_{1}".format(os.getcwd(), date)

		self.input = os.getcwd()
		self.dev, self.act = args.device, args.action
		if self.check_blktrace() is False:
			print("{0} blktrace file not found in path '{1}'".format(self.dev, self.input))
			sys.exit(-1)

	def find_file(self, file_path):
		dir = os.path.dirname(file_path)
		file = os.path.split(file_path)[-1]
		files = os.listdir(dir)
		for f in files:
			if file in f:				
				return os.path.join(dir, f)

		print("file {0} not found in {1}".format(file, dir))
		return file

	def show_statistics(self, file, result):
		type = file.split(".")[-1]
		if self.btt_class.has_key(type) is True:
			print(self.btt_class[type])
			for second in sorted(result):
				info = result[second]
				print("%3d: %9.0f %9.0f" % (second, info[0]/info[1], info[2]))

	def parse_btt(self, file):
		btt_file = self.find_file(file)

		# {second: [sum, count, max]}
		result = {}

		f = open(btt_file, 'r')
		while True:
			lines = f.readlines(10000)
			if not lines:
				break
			for line in lines:
				time, latency = line.split()
				latencies = float(latency)
				sec = int(float(time))
				if result.has_key(sec) is True:
					result[sec][0] += latencies
					result[sec][1] += 1
					if result[sec][2] < latencies:
						result[sec][2] = latencies
				else:
					result[sec] = [latencies, 1, 0]
		f.close
		self.show_statistics(file, result)

	def run(self):
		rc = RunCmd(self.act)
		rc.run("mkdir -p {0}".format(self.output))

		blkp_out_file = "{0}/{1}.blkparse.out".format(self.output, self.dev)
		btt_out_file = "{0}/{1}.btt.out".format(self.output, self.dev)
		btt_q2d_file = "{0}/{1}.btt.q2d_latencies".format(self.output, self.dev)
		btt_d2c_file = "{0}/{1}.btt.d2c_latencies".format(self.output, self.dev)
		btt_q2c_file = "{0}/{1}.btt.q2c_latencies".format(self.output, self.dev)
		btt_aqd_file = "{0}/{1}.btt.active-queue-depth".format(self.output, self.dev)

		rc.run("blkparse -i {0} -d {1}".format(self.dev, blkp_out_file))
		rc.run("btt -i {0} -o {1}".format(blkp_out_file, btt_out_file))
		rc.run("btt -i {0} -z {1}".format(blkp_out_file, btt_q2d_file))
		rc.run("btt -i {0} -l {1}".format(blkp_out_file, btt_d2c_file))
		rc.run("btt -i {0} -q {1}".format(blkp_out_file, btt_q2c_file))
		rc.run("btt -i {0} -Q {1}".format(blkp_out_file, btt_aqd_file))
		
		self.parse_btt(btt_q2d_file)
		self.parse_btt(btt_d2c_file)
		self.parse_btt(btt_q2c_file)
		self.parse_btt(btt_aqd_file)

class MpStat:
	'''
	read mpstat_log file and show the lines which idle is >= 95%
	./sak mpstat -f mpstat_log -i idle -r 95
	'''
	choices = ['usr', 'nice', 'sys', 'iowait', 'irq', 'soft', 'steal', 'guest', 'gnice', 'idle']
	not_data_line = ['CPU', 'all', 'Average']
	choices_dict = {}
	field_offset = 3

	def get_header(self):
		with open(self.logfile, "r") as f:
			lines = f.readlines(10)
			for line in lines:
				if "CPU" in line and "%usr" in line:
					line = line.strip('\n')
					blank_num = line.find('CPU')
					blank = " " * blank_num
					self.header = blank + line[blank_num: ]
					# print("{0}".format(line))
					# print(self.header)
					return

	def get_col_dict(self):
		head_list = self.header.split()
		for i in range(1, len(head_list)):
			h = head_list[i].split('%')[1]
			self.choices_dict[h] = i - 1 + self.field_offset
		# print(self.choices_dict)

	def __init__(self, args):	
		self.logfile, self.field, self.ratio = args.logfile, args.field, args.ratio
		self.get_header()
		self.get_col_dict()
		
	def is_per_cpu_data(self, line):
		if len(line) == 0:
			return False

		for i in self.not_data_line:
			if i in line:
				return False

		return True

	def check_mpstat(self):
		HEADER_PRINT = 1
		line_no = 1
		index = self.choices_dict[self.field]
		# print("index: {0}".format(index))
		with open(self.logfile) as f:
			lines = f.readlines()
			for line in lines:
				line = line.strip('\n')
				debug = "[notdata]"
				if self.is_per_cpu_data(line) is True:
					cpu_info = line.split()
					debug = "[filter ]"
					if float(cpu_info[index]) >= float(self.ratio):
						if HEADER_PRINT == 1:
							HEADER_PRINT = 0
							print("%s" % (self.header))
						debug = "[matched]"
						print("%s" % (line.strip('\n')))
				line_no += 1
		
	def run(self):
		print("checking {0} which '{1}' field >= {2}%".format(self.logfile, self.field, self.ratio))
		self.check_mpstat()

class IrqSmpAffinity:
	PROC_IRQ_PATH = "/proc/irq/"

	def __init__(self, args):
		self.count, self.interval = args.count, args.interval
		self.include, self.exclude = args.include, args.exclude
		if len(self.include) and len(self.exclude):
			result = list(set(self.include) & set(self.exclude))
			# print(self.include, len(self.include), self.exclude, len(self.exclude), result, len(result))
			if len(result) != 0:
				print("paramters conflict! intersection is {0}".format(result))
				sys.exit(-1)

	def get_irq_cpu_list(self, smp_affinity_list):
		cpu_list = "failed"
		with open(smp_affinity_list) as f:
			cpu_list = f.read().strip("\n")

		return cpu_list
			
	def show_irq_affinity(self, irq):
		file = self.PROC_IRQ_PATH + irq + "/smp_affinity_list"
		if os.path.exists(file) is False:
			return

		cpu_list = self.get_irq_cpu_list(file)
		print("[irq: {0:3}]: {1}".format(irq, cpu_list))
